### ISSUE TITLE
Possible App or Guide

### ISSUE THREAD

**Issue by yeenoffthebone** [GoneUp/mask-go#1]
Some boards ain't supported with Tinygo. The ESP32 has Bluetooth but isn't supported. So wondering if it was possible to make an app or guide.

**Comment by GoneUp** [comment]
Hi,
I tested it only with Windows/Linux as this was my usecase, additionally the boards supported by tinygo should work (but I never tested this, as I don't have the relevant boards). 
For ESP32 I can just say that you either need to hope that someone implements the support in tinygo or you switch out the underlying BT library, if there is a supported one (which I don't know)
